name: "ES lint"
description: "Installs dependencies and ES lint"
inputs:
  node-version:
    description: "Node.js version to use"
    required: true
    default: "18"
runs:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash
    - run: npm run test
      shell: bash