name: 'Build projdect'
description: 'Installs dependencies ,build project and deploy'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '18'
runs:
  using: "composite"
  steps:
  
    - run: npm ci
      shell: bash

    - run: npm run build
      shell: bash