name: 'Install dependencies'
description: 'Installs dependencies'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '18'
runs:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash