name: 'Run commitlint tests'
description: 'Installs dependencies and runs e2e tests'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '18'
runs:
  using: "composite"
  steps:
  
    - run: npm ci
      shell: bash

    - run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      shell: bash