name: lint commits
run-name: lint commits
on: [push, pull_request]
jobs:
  commitlint:
    name: commitlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: nm
        
      - name: cli conventionalcommits
        run: npm i -g @commitlint/cli @commitlint/config-conventional conventional-changelog-conventionalcommits

      - name: check commits
        run: |
          if [[ ${{ github.event_name }} == 'push' ]]; then
            npx commitlint --from HEAD~1 --to HEAD --verbose
          elif [[ ${{ github.event_name }} == 'pull_request' ]]; then
            npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
          fi
