name: Issue
run-name: issue
on: [workflow_call]

jobs:
  issue:
    name: Issue
    runs-on: ubuntu-latest
    # needs: create_release_branch
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Define tags
        id: get_tags
        run: |
          CURRENT_TAG=${{ github.ref_name }} 
          TIMESTAMP=$(git show -s --format=%ai ${CURRENT_TAG})
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 ${CURRENT_TAG}^)
          echo "current=${CURRENT_TAG}" >> "$GITHUB_OUTPUT"
          echo "previous=${PREVIOUS_TAG}" >> "$GITHUB_OUTPUT"
          echo "timestamp=${TIMESTAMP}" >> "$GITHUB_OUTPUT"

      - name: Generate changelog
        id: generate_log
        run: |
          CHANGELOG=$(git log --pretty=format:"- %s" "${{ steps.get_tags.outputs.previous }}...${{ steps.get_tags.outputs.current }}")
          echo "Display changelog:"
          echo $CHANGELOG
          echo "log<<EOF" >> $GITHUB_OUTPUT
          echo "${CHANGELOG}" >> "$GITHUB_OUTPUT"
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Issue
        run: |
          ISSUE_TITLE="Release ${{ github.ref_name }}"
          ISSUE_BODY=$(cat << EOF
          ### Version ${{ github.ref_name }}
          Author ${{ github.actor }}
          Date: ${{ steps.get_tags.outputs.timestamp }}
          Changelog:
          ${{ steps.generate_log.outputs.log }}
          Enter into the actions
          [Deploy application](https://github.com/Beksultan/unit-demo-cra/actions/workflows/build.yml)
          EOF
          )

          ISSUE_ID=$(gh issue list --json number,title,labels -q \
            ".[] | select(.title == \"${ISSUE_TITLE}\" and .labels[].name == \"RELEASE\") | .number")
          if [ ! -z "$ISSUE_ID" ]; then
            echo "Editing existing issue"
            gh issue edit $ISSUE_ID --body "$ISSUE_BODY"
          else
            echo "Creating new issue"
            gh issue create --title "Release ${{ github.ref_name }}" --body "$ISSUE_BODY" --label "RELEASE" --assignee "@me"
          fi

            
