name: Release process - Issue
run-name: issue
on: [workflow_call]

jobs:
  issue:
    runs-on: ubuntu-latest
    # needs: check-tests
    permissions:
      issues: write
      pull-requests: write
    outputs:
      issue_number: ${{ steps.create_issue.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install auto-changelog
        run: npm i -g auto-changelog
      - name: Generate changelog
        run: auto-changelog --commit-limit false --template keepachangelog
      - name: Create Issue
        id: create_issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues[existingIssue
              ? 'update'
              : 'create']({
              owner: process.env.GITHUB_REPOSITORY.split('/')[0],
              repo: process.env.GITHUB_REPOSITORY.split('/')[1],
              issue_number: existingIssue?.number,
              title: `Release ${process.env.GITHUB_REF} by ${process.env.GITHUB_ACTOR}`,
              body: require('fs').readFileSync('CHANGELOG.md', 'utf8'),
              state: existingIssue ? 'open' : undefined,
              labels: ['RELEASE'],
            });
