name: Release process - Pull Request

on: [workflow_call]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # - name: Initialize git config, checkout, and push
      #   run: |
      #     git config user.name "GitHub Actions" && git config user.email noreply@github.com && git checkout -b release-${{ github.ref_name }} && git push origin release-${{ github.ref_name }}

      - name: Create or Update Pull Request
        id: create_or_update_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const [o,r]=process.env.GITHUB_REPOSITORY.split('/'),
            b='master',h=`release-${process.env.GITHUB_REF}`,
            p=`Ppull-request #`+process.env.GITHUB_REF,
            t=`Release ${h} by ${process.env.GITHUB_ACTOR}`,
            i={owner:o,repo:r,state:'open',head:`${o}:${h}`},
            u=await github.rest.pulls.list(i),
            e=u.data.find(t=>t.title===t);
            e?await github.rest.pulls.update({owner:o,repo:r,pull_number:e.number,body:p}):await github.rest.pulls.create({owner:o,repo:r,base:b,head:h,body:p,title:t});

