name: Release process - Pull Request

on: [workflow_call]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    permissions: write-all
    # needs: issue
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Initialize git config, checkout, and push
        run: |
          git config user.name "GitHub Actions" && git config user.email noreply@github.com && git checkout -b release-${{ github.ref_name }} && git push origin release-${{ github.ref_name }}
