name: pull-request-merge

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  pull-request-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Eslint check
        run: npm run test

      - name: check
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
             if ((await github.checks.listForRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.sha
              })).data.check_runs.some(check => check.conclusion === 'failure')) {
                core.setFailed('There are failing checks. Blocking merge.');
              }
      - name: merge pull 
        if: ${{ failure() }}
        run: echo "Failed Merge." && exit 1