name: Release process
on:
  push:
    tags:
      - "v*"

jobs:
  # check-tests:
  #   name: Check Tests
  #   uses: ./.github/workflows/tests.yml

  issue:
    name: create or update issue
    # needs: check-tests
    uses: ./.github/workflows/issue.yml

  pull-request:
    name: pull-request-main
    uses: ./.github/workflows/pull_request-main.yml

