name: Release process
on:
  push:
    tags:
      - "v*"
jobs:
  # check-tests:
  #   name:  Check Tests
  #   uses: ./.github/workflows/tests.yml
  issue:
    name: create or update issue
    # needs: check-tests
    uses: ./.github/workflows/issue.yml
  # pull-request:
  #   name: main pull request
  #   # needs: issue
  #   uses: ./.github/workflows/pull-request-main.yml
    
  # deploy: 
  #   needs: [issue,pull-request]
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write 
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'
      
  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run build
  #       run: npm run build

  #       if: success()

  #     - name: Deploy to Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./build
  #         publish_branch: gh-pages
  #         allow_empty_commit: true
  #         commit_message: 'Deploy to GitHub Pages'

  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: build
  #         path: build/
  #         retention-days: 30