name: Release process
on:
  push:
    tags:
      - "v*"
 issue:
    runs-on: ubuntu-latest
    needs: check-tests
    permissions:
      issues: write
      pull-requests: write
    outputs:
      issue_number: ${{ steps.create_issue.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get last tag
        id: last_tag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)
      - name: Install auto-changelog
        run: npm i -g auto-changelog
      - name: Generate changelog
        run: |
          last_tag=$(echo "${{ steps.last_tag.outputs.tag }}")
          auto-changelog --commit-limit false --template keepachangelog --output CHANGELOG.md --starting-commit $last_tag
      - name: Create Issue
        id: create_issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const description = fs.readFileSync('CHANGELOG.md', 'utf8');
            const [owner, repo] = '${{ github.repository }}'.split('/');
            const version = '${{ github.ref_name }}';
            const issue = { owner, repo, labels: ['RELEASE'] };
            
            const issues = await github.rest.issues.listForRepo({ ...issue, state: 'all' });

            const existingIssue = issues.data.find(i => i.title === `release version ${version}`);

            if (existingIssue) {
              const update = { ...issue, issue_number: existingIssue.number, body: description, state: 'open' };
              await github.rest.issues.update(update);
              return existingIssue.number;
            } else {
              const create = { ...issue, title: title, body: description };
              const response = await github.rest.issues.create(create);
              return response.data.number;
            }
  pull-requests:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: issue
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Git checkout
        run: |
          git checkout -b release-${{ github.ref_name }}
      - name: Push the branch
        run: git push origin release-${{ github.ref_name }}

      - name: Create or Update Pull Request
        id: create_or_update_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const [owner, repo] = '${{ github.repository }}'.split('/');
            const base = 'master';
            const head = `release-${{ github.ref_name }}`;
            const issue_number = ${{ needs.issue.outputs.issue_number }};
            const prBody = `This is a pull request for release. Closes #` + issue_number;
            const title = `Release ${head} by ${{ github.actor }}`;
            const pr = { owner, repo, base, head, body: prBody, title };
  
            const pulls = await github.rest.pulls.list({ owner, repo, state: 'open', head: `${owner}:${head}` });
            const existingPr = pulls.data.find(p => p.title === title);
  
            if (existingPr) {
              const update = { owner, repo, pull_number: existingPr.number, body: prBody };
              await github.rest.pulls.update(update);
            } else {
              await github.rest.pulls.create({ ...pr });
            }