name: 'Issue Action'
description: 'Action for creating or updating an issue'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true

outputs:
  issue_number:
    description: 'Number of the created or updated issue'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18